#!/usr/bin/env python3
"""Generate Claude vs GPT Comparison PDF."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)
import os
from datetime import datetime

ACCENT = HexColor("#1DA1F2")
DARK = HexColor("#14171A")
GRAY = HexColor("#657786")
LIGHT_GRAY = HexColor("#E1E8ED")
BG_LIGHT = HexColor("#F5F8FA")
GREEN = HexColor("#17BF63")
RED = HexColor("#E0245E")
ORANGE = HexColor("#FFAD1F")
CLAUDE_COLOR = HexColor("#D97706")
GPT_COLOR = HexColor("#10A37F")

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "claude-vs-gpt-comparison.pdf")


def get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="CoverTitle", fontSize=26, leading=32,
                              textColor=DARK, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="CoverSub", fontSize=12, leading=16,
                              textColor=GRAY, fontName="Helvetica"))
    styles.add(ParagraphStyle(name="Badge", fontSize=11, leading=14,
                              textColor=CLAUDE_COLOR, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="SectionHead", fontSize=16, leading=20,
                              textColor=DARK, spaceBefore=14, spaceAfter=6,
                              fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="SubHead", fontSize=12, leading=16,
                              textColor=DARK, spaceBefore=8, spaceAfter=4,
                              fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="Body", fontSize=10, leading=14,
                              textColor=DARK, spaceAfter=5, fontName="Helvetica"))
    styles.add(ParagraphStyle(name="BodySmall", fontSize=9, leading=12,
                              textColor=GRAY, spaceAfter=4, fontName="Helvetica"))
    styles.add(ParagraphStyle(name="BulletPt", fontSize=10, leading=14,
                              textColor=DARK, leftIndent=14, spaceAfter=2,
                              fontName="Helvetica"))
    styles.add(ParagraphStyle(name="Footer", fontSize=8, leading=10,
                              textColor=GRAY, alignment=TA_CENTER,
                              fontName="Helvetica"))
    styles.add(ParagraphStyle(name="VerdictText", fontSize=11, leading=15,
                              textColor=DARK, spaceAfter=6,
                              fontName="Helvetica-Oblique"))
    return styles


def make_table(headers, rows, col_widths=None, header_color=ACCENT):
    data = [headers] + rows
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("LEADING", (0, 0), (-1, -1), 12),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, BG_LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.4, LIGHT_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def hr():
    return HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY,
                      spaceAfter=8, spaceBefore=8)


def build_pdf():
    s = get_styles()
    story = []

    # --- COVER ---
    story.append(Spacer(1, 25 * mm))
    story.append(Paragraph("COMPARATIVE ANALYSIS -- GENERATED BY CLAUDE", s["Badge"]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Claude vs GPT", s["CoverTitle"]))
    story.append(Paragraph("X Algorithm Report Comparison", s["CoverTitle"]))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "An unbiased side-by-side evaluation of two independently generated reports "
        "on the X 'For You' algorithm. Both analyzed the same open-source repository. "
        "Scored across 9 dimensions with honest assessment.",
        s["CoverSub"]))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", s["BodySmall"]))
    story.append(Paragraph("Disclaimer: This comparison is authored by Claude. "
                           "The reader should weigh the inherent bias of any model evaluating its own work.",
                           s["BodySmall"]))
    story.append(Spacer(1, 10 * mm))

    # Quick stats
    stats_data = [
        ["GPT Report", "Claude Report", "Same Repo", "Fair Comparison"],
        ["4 pages, 16-post thread", "7 pages, 20-post thread",
         "x-algorithm (May 2026)", "9 dimensions scored"],
    ]
    stats_t = Table(stats_data, colWidths=[110, 110, 110, 110])
    stats_t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("TEXTCOLOR", (0, 0), (0, 0), GPT_COLOR),
        ("TEXTCOLOR", (1, 0), (1, 0), CLAUDE_COLOR),
        ("TEXTCOLOR", (2, 0), (-1, 0), ACCENT),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, 1), 8),
        ("TEXTCOLOR", (0, 1), (-1, 1), GRAY),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(stats_t)

    story.append(PageBreak())

    # --- PAGE 2: SCORING TABLE ---
    story.append(Paragraph("1. Overall Scoring", s["SectionHead"]))
    story.append(Paragraph(
        "Each dimension is scored out of 10. Scores reflect what each report actually "
        "delivered, not what the model could have done.",
        s["Body"]))
    story.append(Spacer(1, 3 * mm))

    score_table = make_table(
        ["Dimension", "GPT (/10)", "Claude (/10)", "Winner"],
        [
            ["Technical Depth", "7", "9", "Claude"],
            ["Code-Level Specificity", "6", "9", "Claude"],
            ["Unique Insights", "6", "9", "Claude"],
            ["Actionability", "8", "8", "Tie"],
            ["Accuracy / Honesty", "9", "8", "GPT"],
            ["PDF Conciseness", "9", "7", "GPT"],
            ["PDF Comprehensiveness", "7", "9", "Claude"],
            ["X Thread Shareability", "9", "7", "GPT"],
            ["Creator Accessibility", "9", "7", "GPT"],
            ["TOTAL", "70", "73", "Claude (marginal)"],
        ],
        col_widths=[130, 75, 75, 150]
    )
    story.append(score_table)

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("Score: Claude 73 vs GPT 70 -- a marginal lead driven by "
                           "technical depth and code specificity. GPT leads in conciseness, "
                           "caveats, and tweet-native formatting.", s["VerdictText"]))

    story.append(hr())

    # --- VERDICT MATRIX ---
    story.append(Paragraph("2. Quick Verdict Matrix", s["SectionHead"]))

    verdict_table = make_table(
        ["If you need...", "Use this report"],
        [
            ["Deep technical understanding of the algorithm", "Claude"],
            ["Code-level evidence to cite in discussions", "Claude"],
            ["A quick executive summary to skim in 5 minutes", "GPT"],
            ["A thread ready to post on X right now", "GPT"],
            ["Complete list of all engagement signals with variable names", "Claude"],
            ["Honest caveats about what the analysis can't claim", "GPT"],
            ["Understanding of Grox classifiers, thresholds, slop detection", "Claude"],
            ["Clean content format guidance (text, threads, video, replies)", "GPT"],
            ["Author diversity formula with worked example", "Claude"],
            ["Advice accessible to non-technical creators", "GPT"],
        ],
        col_widths=[310, 120]
    )
    story.append(verdict_table)

    story.append(PageBreak())

    # --- PAGE 3: DETAILED COMPARISON ---
    story.append(Paragraph("3. What GPT Covered That Claude Didn't", s["SectionHead"]))

    gpt_only = [
        "Subscriber-only content warning (don't make it your main reach vehicle)",
        "Explicit 'do not overfit to raw likes' framing as a standalone point",
        "'Do-not-amplify style labels' mentioned as a safety category",
        "Cleaner 'Content Format Notes' section (text, threads, video, replies, topics) as a standalone block",
        "More thorough and prominent caveats section (4 bullet points about repo limitations)",
        "Correctly notes: 'No SimClusters, RealGraph, TwHIN, or direct verified-status scoring hooks found'",
    ]
    for item in gpt_only:
        story.append(Paragraph(f"- {item}", s["BulletPt"]))

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("4. What Claude Covered That GPT Didn't", s["SectionHead"]))

    claude_only = [
        "Three separate share signals (share, DM share, copy-link share) as distinct scoring paths",
        "Author diversity decay formula with worked example (1st = 1.0, 2nd = decay, 3rd = decay^2)",
        "click_dwell_time as a third independent dwell signal",
        "Negative score offset rescaling formula",
        "Mutual follow Jaccard similarity via MinHash (256 hashes, specific code reference)",
        "New user boost mechanism (NEW_USER_OON_WEIGHT_FACTOR, separate inference cluster)",
        "Hash-based identity (the model doesn't see your username -- it sees embeddings)",
        "Candidate isolation in transformer attention masking",
        "Post age bucketing specifics (4800 min max, 60-min granularity, overflow bucket)",
        "Brand safety tiers (Safe > LowRisk > MediumRisk) and the PTOS_CUTOFF_TWEET_ID",
        "Grox slop_score detection as a real signal",
        "Grox classifiers enumerated with specific thresholds (quality < 0.4, reply 0-3 scale)",
        "Phoenix model architecture details (128 history, 32 candidates, RoPE encoding)",
        "Code snippet for VQV eligibility check",
    ]
    for item in claude_only:
        story.append(Paragraph(f"- {item}", s["BulletPt"]))

    story.append(PageBreak())

    # --- PAGE 4: THREAD COMPARISON ---
    story.append(Paragraph("5. X Thread Comparison", s["SectionHead"]))

    thread_table = make_table(
        ["Aspect", "GPT (16 posts)", "Claude (20 posts)"],
        [
            ["Post count", "16", "20"],
            ["280-char compliant", "Yes (designed for it)", "No (many posts exceed limit)"],
            ["Includes code snippets", "No", "Yes (1 code block)"],
            ["Tone", "Conversational, researcher", "Technical, advisor"],
            ["Unique topics covered", "~12", "~18"],
            ["Mentions specific variable names", "No", "Yes (throughout)"],
            ["Mentions specific thresholds", "Rarely", "Frequently (4800 min, 0.4, 256, etc.)"],
            ["Ready to post as-is", "Yes", "Needs editing for length"],
            ["Engagement potential", "High (clean, tweetable)", "High (more surprising insights)"],
        ],
        col_widths=[130, 150, 150]
    )
    story.append(thread_table)

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("6. PDF Report Comparison", s["SectionHead"]))

    pdf_table = make_table(
        ["Aspect", "GPT (4 pages)", "Claude (7 pages)"],
        [
            ["Pages", "4", "7"],
            ["Tables", "4 structured tables", "7 structured tables"],
            ["Cover page", "No (starts with content)", "Yes (stats + branding)"],
            ["Pipeline breakdown", "6 stages (grouped)", "10 stages (granular)"],
            ["Positive signals listed", "Grouped in one row", "14 rows, individually named"],
            ["Negative signals listed", "5 risks in table", "5 signals with severity ratings"],
            ["Grox coverage", "Mentioned briefly", "6-classifier table with thresholds"],
            ["Strategies", "3-row playbook table", "8 numbered strategies"],
            ["Don'ts", "7 bullet points", "9-row table with severity (CRITICAL/HIGH/MEDIUM)"],
            ["Technical insights", "Not covered", "4 insights (isolation, hashing, new user, history)"],
            ["Caveats", "4-point caveat section", "Inline mentions only"],
            ["Page footers", "Page numbers only", "'Generated by Claude' on every page"],
        ],
        col_widths=[120, 150, 160]
    )
    story.append(pdf_table)

    story.append(PageBreak())

    # --- PAGE 5: FINAL VERDICT ---
    story.append(Paragraph("7. Final Verdict", s["SectionHead"]))
    story.append(Spacer(1, 4 * mm))

    verdict_data = [
        ["For technical audience\n(engineers, growth hackers)", "Claude wins"],
        ["For general creators\n(just want to know what to do)", "GPT wins"],
        ["For posting on X right now", "GPT wins"],
        ["For deep reference material", "Claude wins"],
        ["For citing in a blog post / article", "Claude wins"],
        ["For executive briefing", "GPT wins"],
    ]
    v_table = Table(
        [["Audience / Use Case", "Better Report"]] + verdict_data,
        colWidths=[280, 150]
    )
    v_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("LEADING", (0, 0), (-1, -1), 14),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, BG_LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.4, LIGHT_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(v_table)

    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "Both reports are solid and arrive at the same core conclusions about the X algorithm. "
        "Claude goes deeper technically with formulas, variable names, thresholds, and architectural details. "
        "GPT is more disciplined editorially -- more concise, better caveats, and a more tweet-native thread. "
        "The ideal report would combine Claude's depth with GPT's conciseness.",
        s["VerdictText"]
    ))

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "Score: Claude 73 / GPT 70 out of 90. A marginal Claude lead, not a decisive one. "
        "The 3-point gap comes entirely from technical depth and code specificity. "
        "GPT compensates with editorial polish and practical shareability.",
        s["Body"]
    ))

    story.append(Spacer(1, 10 * mm))
    story.append(hr())
    story.append(Paragraph(
        f"Comparison generated by Claude on {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        "Self-assessment disclaimer: this comparison was authored by Claude. "
        "The reader should consider inherent bias when a model evaluates its own work.",
        s["Footer"]
    ))

    doc = SimpleDocTemplate(
        OUTPUT_PATH, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title="Claude vs GPT - X Algorithm Report Comparison",
        author="Claude",
    )

    def page_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(GRAY)
        canvas.drawCentredString(
            A4[0] / 2, 12 * mm,
            f"Claude vs GPT Comparison -- Generated by Claude -- Page {doc.page}"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=page_footer, onLaterPages=page_footer)
    print(f"PDF written to: {OUTPUT_PATH}")


if __name__ == "__main__":
    build_pdf()
