#!/usr/bin/env python3
"""Generate X Algorithm Analysis PDF -- by Claude."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os
from datetime import datetime

ACCENT = HexColor("#1DA1F2")
DARK = HexColor("#14171A")
GRAY = HexColor("#657786")
LIGHT_GRAY = HexColor("#E1E8ED")
BG_LIGHT = HexColor("#F5F8FA")
GREEN = HexColor("#17BF63")
RED = HexColor("#E0245E")
ORANGE = HexColor("#FFAD1F")

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "x-algorithm-analysis-claude.pdf")

def get_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="CoverTitle",
        fontSize=28,
        leading=34,
        textColor=DARK,
        spaceAfter=8,
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="CoverSub",
        fontSize=13,
        leading=18,
        textColor=GRAY,
        spaceAfter=4,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="Badge",
        fontSize=11,
        leading=14,
        textColor=ACCENT,
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="SectionHead",
        fontSize=18,
        leading=22,
        textColor=DARK,
        spaceBefore=16,
        spaceAfter=8,
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="SubHead",
        fontSize=13,
        leading=17,
        textColor=DARK,
        spaceBefore=10,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="Body",
        fontSize=10,
        leading=14,
        textColor=DARK,
        spaceAfter=6,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="BodySmall",
        fontSize=9,
        leading=12,
        textColor=GRAY,
        spaceAfter=4,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="BulletItem",
        fontSize=10,
        leading=14,
        textColor=DARK,
        leftIndent=16,
        spaceAfter=3,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="Footer",
        fontSize=8,
        leading=10,
        textColor=GRAY,
        alignment=TA_CENTER,
        fontName="Helvetica",
    ))
    styles.add(ParagraphStyle(
        name="CalloutText",
        fontSize=10,
        leading=14,
        textColor=DARK,
        fontName="Helvetica-Oblique",
        leftIndent=8,
        rightIndent=8,
        spaceAfter=6,
    ))
    return styles


def make_table(headers, rows, col_widths=None):
    data = [headers] + rows
    w = col_widths or [None] * len(headers)
    t = Table(data, colWidths=w, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("LEADING", (0, 0), (-1, -1), 12),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (0, 1), (-1, -1), white),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, BG_LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.4, LIGHT_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def hr():
    return HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY, spaceAfter=8, spaceBefore=8)


def build_pdf():
    s = get_styles()
    story = []

    # --- COVER ---
    story.append(Spacer(1, 30 * mm))
    story.append(Paragraph("GENERATED BY CLAUDE", s["Badge"]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("X 'For You' Algorithm", s["CoverTitle"]))
    story.append(Paragraph("Deep-Dive Analysis Report", s["CoverTitle"]))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "A comprehensive reverse-engineering of the open-source X recommendation system. "
        "Covers Phoenix (Grok-based transformer ranking), Thunder (in-network store), "
        "Home Mixer (orchestration), and Grox (content understanding).",
        s["CoverSub"]
    ))
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(f"Report Date: {datetime.now().strftime('%B %d, %Y')}", s["BodySmall"]))
    story.append(Paragraph("Source: x-algorithm repository (May 2026 release)", s["BodySmall"]))
    story.append(Paragraph("Components: home-mixer/ (Rust), phoenix/ (Python/JAX), thunder/ (Rust), grox/ (Python)", s["BodySmall"]))
    story.append(Spacer(1, 12 * mm))

    stats_data = [
        ["6", "10", "15+", "5"],
        ["Pipeline Stages", "Pre-Score Filters", "Engagement Signals", "Negative Signals"],
    ]
    stats = Table(stats_data, colWidths=[105, 105, 105, 105])
    stats.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 22),
        ("TEXTCOLOR", (0, 0), (-1, 0), ACCENT),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, 1), 8),
        ("TEXTCOLOR", (0, 1), (-1, 1), GRAY),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(stats)

    story.append(PageBreak())

    # --- PAGE 2: HOW IT WORKS ---
    story.append(Paragraph("1. How the Algorithm Works", s["SectionHead"]))
    story.append(Paragraph(
        "The For You feed is assembled through a multi-stage pipeline. Every tweet you see "
        "has survived candidate sourcing, hydration, filtering, ML-based scoring by a Grok-based "
        "transformer (Phoenix), diversity adjustment, and final selection.",
        s["Body"]
    ))
    story.append(Spacer(1, 4 * mm))

    pipeline = make_table(
        ["Stage", "What Happens", "Key Detail"],
        [
            ["1. Query Hydration", "Fetch user context", "Engagement history, follows, mutes, blocks, topics, IP"],
            ["2. Candidate Sourcing", "Retrieve candidates", "Thunder (in-network) + Phoenix Retrieval (out-of-network)"],
            ["3. Hydration", "Enrich metadata", "Author info, media, video duration, engagement counts, mutual follows"],
            ["4. Pre-Score Filtering", "Remove ineligible", "Duplicates, old posts, self-posts, blocked/muted, seen, muted keywords"],
            ["5. Phoenix Scoring", "ML predictions", "Grok transformer predicts 15+ action probabilities per tweet"],
            ["6. Weighted Scoring", "Combine predictions", "Final Score = SUM(weight x P(action)) across all action types"],
            ["7. Author Diversity", "Decay repeats", "Exponential decay multiplier for repeated authors"],
            ["8. OON Adjustment", "Balance networks", "Out-of-network tweets get a scaling factor"],
            ["9. Selection", "Pick top K", "Sort by final score, select top candidates"],
            ["10. Post-Selection", "Safety check", "Visibility filtering, conversation dedup"],
        ],
        col_widths=[85, 95, 250]
    )
    story.append(pipeline)

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("The Core Ranking Formula", s["SubHead"]))
    story.append(Paragraph(
        "<b>Final Score = SUM( weight_i x P(action_i) )</b> -- Phoenix predicts the probability of each "
        "engagement type (like, reply, repost, share, video view, dwell, follow, block, mute, report, etc.) "
        "and these are multiplied by configurable weights. Positive actions boost; negative actions suppress.",
        s["Body"]
    ))

    story.append(PageBreak())

    # --- PAGE 3: POSITIVE SIGNALS ---
    story.append(Paragraph("2. Positive Signals (What Boosts Your Tweet)", s["SectionHead"]))
    story.append(Paragraph(
        "Each signal below has its own weight in the scoring formula. More signal types triggered = higher combined score.",
        s["Body"]
    ))
    story.append(Spacer(1, 3 * mm))

    pos_table = make_table(
        ["Signal", "Code Reference", "Impact"],
        [
            ["P(favorite)", "favorite_score x FAVORITE_WEIGHT", "Very High -- likes are primary"],
            ["P(reply)", "reply_score x REPLY_WEIGHT", "Very High -- conversation signal"],
            ["P(repost)", "retweet_score x RETWEET_WEIGHT", "Very High -- share-worthy content"],
            ["P(quote)", "quote_score x QUOTE_WEIGHT", "High -- thought-provoking"],
            ["P(share)", "share_score x SHARE_WEIGHT", "High -- general sharing"],
            ["P(share_via_DM)", "share_via_dm_score x SHARE_VIA_DM_WEIGHT", "High -- personal value"],
            ["P(share_copy_link)", "share_via_copy_link_score x weight", "High -- off-platform sharing"],
            ["P(click)", "click_score x CLICK_WEIGHT", "Medium -- expanding/links"],
            ["P(profile_click)", "profile_click_score x weight", "Medium -- profile visits"],
            ["P(photo_expand)", "photo_expand_score x weight", "Medium -- image engagement"],
            ["P(video_view)", "vqv_score x VQV_WEIGHT", "Medium-High -- video only, duration gated"],
            ["P(dwell)", "dwell_score x DWELL_WEIGHT", "Medium -- stopped scrolling"],
            ["P(dwell_time)", "dwell_time x CONT_DWELL_TIME_WEIGHT", "Medium -- reading duration"],
            ["P(follow_author)", "follow_author_score x weight", "High -- conversion signal"],
        ],
        col_widths=[90, 180, 160]
    )
    story.append(pos_table)

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("3. Negative Signals (What Kills Your Tweet)", s["SectionHead"]))

    neg_table = make_table(
        ["Signal", "Code Reference", "Impact"],
        [
            ["P(not_interested)", "not_interested_score x NOT_INTERESTED_WEIGHT", "Strong Negative"],
            ["P(block_author)", "block_author_score x BLOCK_AUTHOR_WEIGHT", "Very Strong Negative"],
            ["P(mute_author)", "mute_author_score x MUTE_AUTHOR_WEIGHT", "Strong Negative"],
            ["P(report)", "report_score x REPORT_WEIGHT", "Very Strong Negative"],
            ["P(not_dwelled)", "not_dwelled_score x NOT_DWELLED_WEIGHT", "Moderate Negative"],
        ],
        col_widths=[90, 200, 140]
    )
    story.append(neg_table)
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(
        "When a tweet's combined score goes negative, it is rescaled: "
        "(score + NEGATIVE_WEIGHTS_SUM) / WEIGHTS_SUM x NEGATIVE_SCORES_OFFSET. "
        "The model predicts these for EVERY candidate -- if your past content has a pattern of "
        "triggering blocks, the model generalizes this to your future content.",
        s["BodySmall"]
    ))

    story.append(PageBreak())

    # --- PAGE 4: CONTENT TYPES ---
    story.append(Paragraph("4. Content Types the Algorithm Favors", s["SectionHead"]))

    story.append(Paragraph("Video: Exclusive VQV Scoring", s["SubHead"]))
    story.append(Paragraph(
        "Videos have a dedicated VQV (Video Quality View) signal with its own weight. "
        "Only videos longer than MIN_VIDEO_DURATION_MS qualify -- the code explicitly sets "
        "vqv_weight = 0.0 for short clips. Thunder maintains a separate video_posts_by_user index. "
        "Quoted tweets with video also get special treatment via quoted_vqv_weight.",
        s["Body"]
    ))

    story.append(Paragraph("Images: Dedicated Expansion Signal", s["SubHead"]))
    story.append(Paragraph(
        "Photo expansion (photo_expand_score) is a separate prediction head. The model specifically "
        "learns whether a user will click to expand an image. Posts with compelling images that users "
        "expand get boosted. HasMediaHydrator detects media presence as a boolean feature for the ML model.",
        s["Body"]
    ))

    story.append(Paragraph("Dwell Time: Reading Duration is Measured", s["SubHead"]))
    story.append(Paragraph(
        "Three dwell signals exist: binary dwell (stopped scrolling), continuous dwell_time (how long), "
        "and click_dwell_time (time after clicking in). Write longer, substantive posts that reward careful reading.",
        s["Body"]
    ))

    story.append(hr())

    # --- GROX ---
    story.append(Paragraph("5. Grox Content Safety Pipeline", s["SectionHead"]))
    story.append(Paragraph(
        "Before tweets reach ranking, the Grox system uses Grok VLM classifiers to evaluate content quality and safety.",
        s["Body"]
    ))

    grox_table = make_table(
        ["Classifier", "What It Does", "Impact"],
        [
            ["BangerInitialScreen", "Assigns quality_score (0-1), slop_score, tags, taxonomy", "Below 0.4 quality = flagged"],
            ["SpamClassifier", "Targets low-follower accounts for spam detection", "Spam = removed from feed"],
            ["SafetyPTOS Category", "Checks 7 safety policy categories", "Violations dropped by VFFilter"],
            ["SafetyPTOS Policy", "Per-policy analysis with reasoning fallback", "ViolentMedia, AdultContent, Spam, Hate, etc."],
            ["PostSafetyDeluxe", "Extended safety screening", "Produces tweet_bool_metadata"],
            ["ReplyScorer", "Scores reply quality 0-3 scale", "Determines reply visibility"],
        ],
        col_widths=[100, 190, 140]
    )
    story.append(grox_table)

    story.append(PageBreak())

    # --- PAGE 5: HOW TO BOOST REACH ---
    story.append(Paragraph("6. How to Maximize Your Reach on X", s["SectionHead"]))
    story.append(Paragraph(
        "These strategies are derived directly from how the scoring algorithm works in production code.",
        s["CalloutText"]
    ))

    strategies = [
        ("Maximize Multi-Signal Engagement",
         "A tweet with 50 likes + 20 replies + 10 reposts scores higher than 100 likes alone. "
         "The formula is a SUM across all weighted predictions. More signal types = higher combined score."),
        ("Drive DM + Copy Link Shares",
         "Three separate share signals exist. Content people send to friends or copy-paste elsewhere "
         "gets a triple share boost. Create 'you need to see this' content."),
        ("Optimize for Dwell Time",
         "Binary dwell, continuous dwell_time, and click_dwell_time all contribute independently. "
         "Write substantive posts. Include details that reward careful reading."),
        ("Use Video Above Minimum Duration",
         "VQV weight is ONLY applied when duration exceeds MIN_VIDEO_DURATION_MS. Below = 0.0. "
         "This is a bonus signal text and image posts cannot receive."),
        ("Trigger Follow Actions",
         "P(follow_author) is directly in the scoring formula. Establish clear expertise. "
         "The algorithm rewards accounts that convert impressions to follows."),
        ("Post Consistently",
         "Phoenix processes the last 128 engagement actions. Regular posting builds patterns "
         "the transformer relies on. Irregular posting breaks the signal."),
        ("Leverage Mutual Follow Networks",
         "Jaccard similarity between your followers and a viewer's followers (256 MinHash values) "
         "affects out-of-network relevance. Engage with communities in your niche."),
        ("Nail the First Hour",
         "Post age buckets have 60-minute granularity, max 4800 minutes. Thunder retention = 2 days. "
         "Strong engagement in the first bucket signals relevance and compounds."),
    ]

    for i, (title, desc) in enumerate(strategies, 1):
        story.append(Paragraph(f"Strategy {i}: {title}", s["SubHead"]))
        story.append(Paragraph(desc, s["Body"]))

    story.append(PageBreak())

    # --- PAGE 6: THE DON'TS ---
    story.append(Paragraph("7. The Don'ts -- What Kills Your Reach", s["SectionHead"]))

    donts_table = make_table(
        ["Don't", "Why (From Code)", "Severity"],
        [
            ["Trigger blocks/mutes/reports",
             "P(block), P(mute), P(report) have strong NEGATIVE weights. Model generalizes from past patterns.",
             "CRITICAL"],
            ["Make people scroll past",
             "P(not_dwelled) is a negative signal. Consistently skipped content trains the model to demote you.",
             "HIGH"],
            ["Flood the feed",
             "AuthorDiversityScorer: exponential decay. multiplier = (1-floor) x decay^position + floor.",
             "HIGH"],
            ["Post spam / low-quality",
             "Grox SpamClassifier + BangerInitialScreen. quality < 0.4 = flagged. slop_score is real.",
             "CRITICAL"],
            ["Use muted keywords",
             "MutedKeywordFilter tokenizes text and matches. Tweet invisible to anyone who muted a keyword you used.",
             "HIGH"],
            ["Violate safety policies",
             "VFFilter removes flagged tweets. 7 policy categories checked by SafetyPTOS.",
             "CRITICAL"],
            ["Post short throwaway videos",
             "Videos below MIN_VIDEO_DURATION_MS: vqv_weight = 0.0. Entire VQV scoring signal lost.",
             "MEDIUM"],
            ["Ignore early engagement",
             "Phoenix 128-action history window. No early engagement = not in histories = not in future ranking.",
             "HIGH"],
            ["Trigger 'Not Interested'",
             "Dedicated negative signal. Pattern of 'Not Interested' creates a downward spiral.",
             "HIGH"],
        ],
        col_widths=[120, 230, 80]
    )
    story.append(donts_table)

    story.append(PageBreak())

    # --- PAGE 7: TECHNICAL INSIGHTS + PLAYBOOK ---
    story.append(Paragraph("8. Key Technical Insights", s["SectionHead"]))

    insights = [
        ("Candidate Isolation",
         "In the Phoenix transformer, candidates cannot attend to each other -- only to user context. "
         "Your tweet is scored independently. Scores are purely a function of (your content x this specific user's history)."),
        ("Hash-Based Identity",
         "Users and posts are represented through multiple hash embeddings (2 user, 2 item, 2 author hashes default). "
         "The model doesn't see your username -- it sees embedding patterns learned from engagement."),
        ("New User Boost",
         "Users below PhoenixRankerNewUserHistoryThreshold route to a different inference cluster. "
         "New users also get NEW_USER_OON_WEIGHT_FACTOR for out-of-network content if they follow enough accounts."),
        ("Engagement History Window",
         "128 engagement actions (history_seq_len=128), up to 32 candidates at once (candidate_seq_len=32). "
         "RoPE positional encoding with right-anchored option giving newest history items fixed positions."),
    ]
    for title, desc in insights:
        story.append(Paragraph(title, s["SubHead"]))
        story.append(Paragraph(desc, s["Body"]))

    story.append(hr())

    story.append(Paragraph("9. Final Playbook", s["SectionHead"]))

    playbook_do = [
        "Trigger multiple engagement types (likes + replies + reposts + shares)",
        "Post qualifying-length video for the exclusive VQV scoring bonus",
        "Maximize dwell time with substantive, detailed content",
        "Drive DM shares and copy-link shares (3 separate scoring signals)",
        "Optimize for the follow action -- P(follow_author) is in the formula",
        "Post consistently to build engagement history patterns",
        "Stay in your niche for retrieval model clarity",
    ]
    playbook_dont = [
        "Trigger blocks/mutes/reports (strongest negative weights)",
        "Get flagged by Grox safety classifiers (content removed entirely)",
        "Post low-quality content (quality < 0.4 flagged, slop detection is real)",
        "Flood with posts (author diversity decay is exponential)",
        "Create scroll-past content (not_dwelled trains the model against you)",
    ]

    story.append(Paragraph("TOP DO's:", s["SubHead"]))
    for i, item in enumerate(playbook_do, 1):
        story.append(Paragraph(f"  {i}. {item}", s["BulletItem"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("TOP DON'Ts:", s["SubHead"]))
    for i, item in enumerate(playbook_dont, 1):
        story.append(Paragraph(f"  {i}. {item}", s["BulletItem"]))

    story.append(Spacer(1, 12 * mm))
    story.append(hr())
    story.append(Paragraph(
        f"Generated by Claude on {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        "Source: x-algorithm repository (May 2026 release) | "
        "Components: home-mixer/ (Rust), phoenix/ (Python/JAX), thunder/ (Rust), grox/ (Python), candidate-pipeline/ (Rust)",
        s["Footer"]
    ))

    doc = SimpleDocTemplate(
        OUTPUT_PATH,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="X Algorithm Analysis - Generated by Claude",
        author="Claude",
    )

    def add_page_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(GRAY)
        canvas.drawCentredString(
            A4[0] / 2, 12 * mm,
            f"X Algorithm Analysis -- Generated by Claude -- Page {doc.page}"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_footer, onLaterPages=add_page_footer)
    print(f"PDF written to: {OUTPUT_PATH}")


if __name__ == "__main__":
    build_pdf()
